// Code generated by goctl. DO NOT EDIT.
package types

type BaseResponse struct {
	Code    int64  `json:"status_code"`
	Message string `json:"status_msg,omitempty"`
}

type RegisterReq struct {
	Username string `form:"username" validate:"required,max=32,min=4"`
	Password string `form:"password" validate:"required,max=32,min=8"`
}

type RegisterResp struct {
	BaseResponse
	UserId int64  `json:"user_id"`
	Token  string `json:"token"`
}

type LoginReq struct {
	Username string `form:"username" validate:"required,max=32,min=4"`
	Password string `form:"password" validate:"required,max=32,min=8"`
}

type LoginResp struct {
	BaseResponse
	UserId int64  `json:"user_id"`
	Token  string `json:"token"`
}

type UserInfoReq struct {
	UserId int64  `json:"user_id"`
	Token  string `json:"token"`
}

type UserInfoResp struct {
	BaseResponse
	ID              int64  `json:"id"`
	Name            string `json:"name"`
	FollowCount     int64  `json:"follow_count"`
	FollowerCount   int64  `json:"follower_count"`
	IsFollow        bool   `json:"is_follow"`
	Avatar          string `json:"avatar"`
	BackgroundImage string `json:"background_image"`
	Signature       string `json:"signature"`
	TotalFavorited  string `json:"total_favorited"`
	WorkCount       int64  `json:"work_count"`
	FavoriteCount   int64  `json:"favorite_count"`
}
