// Code generated by goctl. DO NOT EDIT.
package types

type BaseResponse struct {
	Code    int64  `json:"status_code"`
	Message string `json:"status_msg,omitempty"`
}

type RegisterReq struct {
	Username string `form:"username" validate:"required,max=32,min=4"`
	Password string `form:"password" validate:"required,max=32,min=8"`
}

type RegisterResp struct {
	BaseResponse
	UserId int64  `json:"user_id"`
	Token  string `json:"token"`
}

type LoginReq struct {
	Username string `form:"username" validate:"required,max=32,min=4"`
	Password string `form:"password" validate:"required,max=32,min=8"`
}

type LoginResp struct {
	BaseResponse
	UserId int64  `json:"user_id"`
	Token  string `json:"token"`
}
