// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"GopherTok/server/comment/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/douyin/comment/action",
					Handler: CommentActionHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/douyin/comment/list",
					Handler: CommentListHandler(serverCtx),
				},
			}...,
		),
	)
}
