// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	messageFieldNames          = builder.RawFieldNames(&Message{})
	messageRows                = strings.Join(messageFieldNames, ",")
	messageRowsExpectAutoSet   = strings.Join(stringx.Remove(messageFieldNames, "`create_at`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	messageRowsWithPlaceHolder = strings.Join(stringx.Remove(messageFieldNames, "`id`", "`create_at`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheDouyinChatMessageIdPrefix = "cache:douyinChat:message:id:"
)

type (
	messageModel interface {
		Insert(ctx context.Context, data *Message) (sql.Result, error)
		TxInsert(ctx context.Context, tx sqlx.Session, data *Message) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Message, error)
		Update(ctx context.Context, data *Message) error
		Delete(ctx context.Context, id int64) error
	}

	defaultMessageModel struct {
		sqlc.CachedConn
		table string
	}

	Message struct {
		Id         int64  `db:"id"`
		FromUserId int64  `db:"from_user_id"`
		ToUserId   int64  `db:"to_user_id"`
		Content    string `db:"content"`
		CreateTime int64  `db:"create_time"`
	}
)

func newMessageModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultMessageModel {
	return &defaultMessageModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`message`",
	}
}

func (m *defaultMessageModel) Delete(ctx context.Context, id int64) error {
	douyinChatMessageIdKey := fmt.Sprintf("%s%v", cacheDouyinChatMessageIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, douyinChatMessageIdKey)
	return err
}

func (m *defaultMessageModel) FindOne(ctx context.Context, id int64) (*Message, error) {
	douyinChatMessageIdKey := fmt.Sprintf("%s%v", cacheDouyinChatMessageIdPrefix, id)
	var resp Message
	err := m.QueryRowCtx(ctx, &resp, douyinChatMessageIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", messageRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMessageModel) Insert(ctx context.Context, data *Message) (sql.Result, error) {
	douyinChatMessageIdKey := fmt.Sprintf("%s%v", cacheDouyinChatMessageIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, messageRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.FromUserId, data.ToUserId, data.Content, data.CreateTime)
	}, douyinChatMessageIdKey)
	return ret, err
}

func (m *defaultMessageModel) TxInsert(ctx context.Context, tx sqlx.Session, data *Message) (sql.Result, error) {
	douyinChatMessageIdKey := fmt.Sprintf("%s%v", cacheDouyinChatMessageIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, messageRowsExpectAutoSet)
		return tx.ExecCtx(ctx, query, data.FromUserId, data.ToUserId, data.Content)
	}, douyinChatMessageIdKey)
	return ret, err
}

func (m *defaultMessageModel) Update(ctx context.Context, data *Message) error {
	douyinChatMessageIdKey := fmt.Sprintf("%s%v", cacheDouyinChatMessageIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, messageRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.FromUserId, data.ToUserId, data.Content, data.Id)
	}, douyinChatMessageIdKey)
	return err
}

func (m *defaultMessageModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheDouyinChatMessageIdPrefix, primary)
}

func (m *defaultMessageModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", messageRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultMessageModel) tableName() string {
	return m.table
}
