// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"GopherTok/server/relation/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{}, //serverCtx.Jwt
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/douyin/relation/action",
					Handler: FollowHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/douyin/relation/follow/list",
					Handler: FollowListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/douyin/relation/follower/list",
					Handler: FollowerListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/douyin/relation/friend/list",
					Handler: FriendListHandler(serverCtx),
				},
			}...,
		),
	)
}
