// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"
	"time"

	"GopherTok/server/video/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWT},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/action",
					Handler: PublishVideoHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: UserVideoListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/douyin/publish"), rest.WithTimeout(9999999000*time.Millisecond),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/feed",
				Handler: VideoListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/douyin"),
	)
}
