// Code generated by goctl. DO NOT EDIT.
// Source: video.proto

package server

import (
	"context"

	"GopherTok/server/video/rpc/internal/logic"
	"GopherTok/server/video/rpc/internal/svc"
	"GopherTok/server/video/rpc/types/video"
)

type VideoServer struct {
	svcCtx *svc.ServiceContext
	video.UnimplementedVideoServer
}

func NewVideoServer(svcCtx *svc.ServiceContext) *VideoServer {
	return &VideoServer{
		svcCtx: svcCtx,
	}
}

func (s *VideoServer) PublishVideo(ctx context.Context, in *video.PublishVideoReq) (*video.CommonResp, error) {
	l := logic.NewPublishVideoLogic(ctx, s.svcCtx)
	return l.PublishVideo(in)
}

func (s *VideoServer) UserVideoList(ctx context.Context, in *video.UserVideoListReq) (*video.UserVideoListResp, error) {
	l := logic.NewUserVideoListLogic(ctx, s.svcCtx)
	return l.UserVideoList(in)
}

func (s *VideoServer) VideoList(ctx context.Context, in *video.VideoListReq) (*video.VideoListResp, error) {
	l := logic.NewVideoListLogic(ctx, s.svcCtx)
	return l.VideoList(in)
}
