// Code generated by goctl. DO NOT EDIT.
// Source: relation.proto

package streamgreeter

import (
	"context"

	"GopherTok/server/relation/rpc/types/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddFollowReq      = pb.AddFollowReq
	AddFollowResp     = pb.AddFollowResp
	CheckIsFollowReq  = pb.CheckIsFollowReq
	CheckIsFollowResp = pb.CheckIsFollowResp
	DeleteFollowReq   = pb.DeleteFollowReq
	DeleteFollowResp  = pb.DeleteFollowResp
	FollowSubject     = pb.FollowSubject
	GetFollowListReq  = pb.GetFollowListReq
	GetFollowListResp = pb.GetFollowListResp
	GetFollowerReq    = pb.GetFollowerReq
	GetFollowerResp   = pb.GetFollowerResp
	GetFriendListReq  = pb.GetFriendListReq
	GetFriendListResp = pb.GetFriendListResp
	User              = pb.User

	StreamGreeter interface {
		AddFollow(ctx context.Context, in *AddFollowReq, opts ...grpc.CallOption) (*AddFollowResp, error)
		DeleteFollow(ctx context.Context, in *DeleteFollowReq, opts ...grpc.CallOption) (*DeleteFollowResp, error)
		GetFollowList(ctx context.Context, in *GetFollowListReq, opts ...grpc.CallOption) (*GetFollowListResp, error)
		GetFollowerList(ctx context.Context, in *GetFollowerReq, opts ...grpc.CallOption) (*GetFollowerResp, error)
		GetFriendList(ctx context.Context, in *GetFriendListReq, opts ...grpc.CallOption) (*GetFriendListResp, error)
	}

	defaultStreamGreeter struct {
		cli zrpc.Client
	}
)

func NewStreamGreeter(cli zrpc.Client) StreamGreeter {
	return &defaultStreamGreeter{
		cli: cli,
	}
}

func (m *defaultStreamGreeter) AddFollow(ctx context.Context, in *AddFollowReq, opts ...grpc.CallOption) (*AddFollowResp, error) {
	client := pb.NewStreamGreeterClient(m.cli.Conn())
	return client.AddFollow(ctx, in, opts...)
}

func (m *defaultStreamGreeter) DeleteFollow(ctx context.Context, in *DeleteFollowReq, opts ...grpc.CallOption) (*DeleteFollowResp, error) {
	client := pb.NewStreamGreeterClient(m.cli.Conn())
	return client.DeleteFollow(ctx, in, opts...)
}

func (m *defaultStreamGreeter) GetFollowList(ctx context.Context, in *GetFollowListReq, opts ...grpc.CallOption) (*GetFollowListResp, error) {
	client := pb.NewStreamGreeterClient(m.cli.Conn())
	return client.GetFollowList(ctx, in, opts...)
}

func (m *defaultStreamGreeter) GetFollowerList(ctx context.Context, in *GetFollowerReq, opts ...grpc.CallOption) (*GetFollowerResp, error) {
	client := pb.NewStreamGreeterClient(m.cli.Conn())
	return client.GetFollowerList(ctx, in, opts...)
}

func (m *defaultStreamGreeter) GetFriendList(ctx context.Context, in *GetFriendListReq, opts ...grpc.CallOption) (*GetFriendListResp, error) {
	client := pb.NewStreamGreeterClient(m.cli.Conn())
	return client.GetFriendList(ctx, in, opts...)
}
