// Code generated by goctl. DO NOT EDIT.
// Source: relation.proto

package server

import (
	"context"

	"GopherTok/server/relation/rpc/internal/logic"
	"GopherTok/server/relation/rpc/internal/svc"
	"GopherTok/server/relation/rpc/types/pb"
)

type StreamGreeterServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedStreamGreeterServer
}

func NewStreamGreeterServer(svcCtx *svc.ServiceContext) *StreamGreeterServer {
	return &StreamGreeterServer{
		svcCtx: svcCtx,
	}
}

func (s *StreamGreeterServer) AddFollow(ctx context.Context, in *pb.AddFollowReq) (*pb.AddFollowResp, error) {
	l := logic.NewAddFollowLogic(ctx, s.svcCtx)
	return l.AddFollow(in)
}

func (s *StreamGreeterServer) DeleteFollow(ctx context.Context, in *pb.DeleteFollowReq) (*pb.DeleteFollowResp, error) {
	l := logic.NewDeleteFollowLogic(ctx, s.svcCtx)
	return l.DeleteFollow(in)
}

func (s *StreamGreeterServer) GetFollowList(ctx context.Context, in *pb.GetFollowListReq) (*pb.GetFollowListResp, error) {
	l := logic.NewGetFollowListLogic(ctx, s.svcCtx)
	return l.GetFollowList(in)
}

func (s *StreamGreeterServer) GetFollowerList(ctx context.Context, in *pb.GetFollowerReq) (*pb.GetFollowerResp, error) {
	l := logic.NewGetFollowerListLogic(ctx, s.svcCtx)
	return l.GetFollowerList(in)
}

func (s *StreamGreeterServer) GetFriendList(ctx context.Context, in *pb.GetFriendListReq) (*pb.GetFriendListResp, error) {
	l := logic.NewGetFriendListLogic(ctx, s.svcCtx)
	return l.GetFriendList(in)
}
