// Code generated by goctl. DO NOT EDIT.
package types

type BaseResponse struct {
	Code    int64  `json:"status_code"`
	Message string `json:"status_msg,omitempty"`
}

type FavorReq struct {
	User_id  int64 `json:"userId"`
	Video_id int64 `json:"videoId"`
}

type FavorResp struct {
	BaseResponse
}

type DisFavorReq struct {
	User_id  int64 `json:"userId"`
	Video_id int64 `json:"videoId"`
}

type DisFavorResp struct {
	BaseResponse
}

type FavorlistReq struct {
	UserId int64 `form:"user_id"`
}

type FavorlistResp struct {
	BaseResponse
	Video_ids []int64 `json:"videoIds"`
}

type FavorNumReq struct {
	Video_id int64 `json:"videoId"`
}

type FavorNumResp struct {
	BaseResponse
	FavorNum int64 `json:"FavorNum"`
}
