// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RelationRpcClient is the client API for RelationRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RelationRpcClient interface {
	AddFollow(ctx context.Context, in *AddFollowReq, opts ...grpc.CallOption) (*AddFollowResp, error)
	DeleteFollow(ctx context.Context, in *DeleteFollowReq, opts ...grpc.CallOption) (*DeleteFollowResp, error)
	GetFollowList(ctx context.Context, in *GetFollowListReq, opts ...grpc.CallOption) (*GetFollowListResp, error)
	GetFollowerList(ctx context.Context, in *GetFollowerReq, opts ...grpc.CallOption) (*GetFollowerResp, error)
	GetFriendList(ctx context.Context, in *GetFriendListReq, opts ...grpc.CallOption) (*GetFriendListResp, error)
	GetFollowerCount(ctx context.Context, in *GetFollowerCountReq, opts ...grpc.CallOption) (*GetFollowerCountResp, error)
	GetFollowCount(ctx context.Context, in *GetFollowCountReq, opts ...grpc.CallOption) (*GetFollowCountResp, error)
	GetFriendCount(ctx context.Context, in *GetFriendCountReq, opts ...grpc.CallOption) (*GetFriendCountResp, error)
	CheckIsFollow(ctx context.Context, in *CheckIsFollowReq, opts ...grpc.CallOption) (*CheckIsFollowResp, error)
}

type relationRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewRelationRpcClient(cc grpc.ClientConnInterface) RelationRpcClient {
	return &relationRpcClient{cc}
}

func (c *relationRpcClient) AddFollow(ctx context.Context, in *AddFollowReq, opts ...grpc.CallOption) (*AddFollowResp, error) {
	out := new(AddFollowResp)
	err := c.cc.Invoke(ctx, "/relation.RelationRpc/AddFollow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relationRpcClient) DeleteFollow(ctx context.Context, in *DeleteFollowReq, opts ...grpc.CallOption) (*DeleteFollowResp, error) {
	out := new(DeleteFollowResp)
	err := c.cc.Invoke(ctx, "/relation.RelationRpc/DeleteFollow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relationRpcClient) GetFollowList(ctx context.Context, in *GetFollowListReq, opts ...grpc.CallOption) (*GetFollowListResp, error) {
	out := new(GetFollowListResp)
	err := c.cc.Invoke(ctx, "/relation.RelationRpc/GetFollowList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relationRpcClient) GetFollowerList(ctx context.Context, in *GetFollowerReq, opts ...grpc.CallOption) (*GetFollowerResp, error) {
	out := new(GetFollowerResp)
	err := c.cc.Invoke(ctx, "/relation.RelationRpc/GetFollowerList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relationRpcClient) GetFriendList(ctx context.Context, in *GetFriendListReq, opts ...grpc.CallOption) (*GetFriendListResp, error) {
	out := new(GetFriendListResp)
	err := c.cc.Invoke(ctx, "/relation.RelationRpc/GetFriendList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relationRpcClient) GetFollowerCount(ctx context.Context, in *GetFollowerCountReq, opts ...grpc.CallOption) (*GetFollowerCountResp, error) {
	out := new(GetFollowerCountResp)
	err := c.cc.Invoke(ctx, "/relation.RelationRpc/GetFollowerCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relationRpcClient) GetFollowCount(ctx context.Context, in *GetFollowCountReq, opts ...grpc.CallOption) (*GetFollowCountResp, error) {
	out := new(GetFollowCountResp)
	err := c.cc.Invoke(ctx, "/relation.RelationRpc/GetFollowCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relationRpcClient) GetFriendCount(ctx context.Context, in *GetFriendCountReq, opts ...grpc.CallOption) (*GetFriendCountResp, error) {
	out := new(GetFriendCountResp)
	err := c.cc.Invoke(ctx, "/relation.RelationRpc/GetFriendCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relationRpcClient) CheckIsFollow(ctx context.Context, in *CheckIsFollowReq, opts ...grpc.CallOption) (*CheckIsFollowResp, error) {
	out := new(CheckIsFollowResp)
	err := c.cc.Invoke(ctx, "/relation.RelationRpc/CheckIsFollow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RelationRpcServer is the server API for RelationRpc service.
// All implementations must embed UnimplementedRelationRpcServer
// for forward compatibility
type RelationRpcServer interface {
	AddFollow(context.Context, *AddFollowReq) (*AddFollowResp, error)
	DeleteFollow(context.Context, *DeleteFollowReq) (*DeleteFollowResp, error)
	GetFollowList(context.Context, *GetFollowListReq) (*GetFollowListResp, error)
	GetFollowerList(context.Context, *GetFollowerReq) (*GetFollowerResp, error)
	GetFriendList(context.Context, *GetFriendListReq) (*GetFriendListResp, error)
	GetFollowerCount(context.Context, *GetFollowerCountReq) (*GetFollowerCountResp, error)
	GetFollowCount(context.Context, *GetFollowCountReq) (*GetFollowCountResp, error)
	GetFriendCount(context.Context, *GetFriendCountReq) (*GetFriendCountResp, error)
	CheckIsFollow(context.Context, *CheckIsFollowReq) (*CheckIsFollowResp, error)
	mustEmbedUnimplementedRelationRpcServer()
}

// UnimplementedRelationRpcServer must be embedded to have forward compatible implementations.
type UnimplementedRelationRpcServer struct {
}

func (*UnimplementedRelationRpcServer) AddFollow(context.Context, *AddFollowReq) (*AddFollowResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddFollow not implemented")
}
func (*UnimplementedRelationRpcServer) DeleteFollow(context.Context, *DeleteFollowReq) (*DeleteFollowResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFollow not implemented")
}
func (*UnimplementedRelationRpcServer) GetFollowList(context.Context, *GetFollowListReq) (*GetFollowListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFollowList not implemented")
}
func (*UnimplementedRelationRpcServer) GetFollowerList(context.Context, *GetFollowerReq) (*GetFollowerResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFollowerList not implemented")
}
func (*UnimplementedRelationRpcServer) GetFriendList(context.Context, *GetFriendListReq) (*GetFriendListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFriendList not implemented")
}
func (*UnimplementedRelationRpcServer) GetFollowerCount(context.Context, *GetFollowerCountReq) (*GetFollowerCountResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFollowerCount not implemented")
}
func (*UnimplementedRelationRpcServer) GetFollowCount(context.Context, *GetFollowCountReq) (*GetFollowCountResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFollowCount not implemented")
}
func (*UnimplementedRelationRpcServer) GetFriendCount(context.Context, *GetFriendCountReq) (*GetFriendCountResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFriendCount not implemented")
}
func (*UnimplementedRelationRpcServer) CheckIsFollow(context.Context, *CheckIsFollowReq) (*CheckIsFollowResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckIsFollow not implemented")
}
func (*UnimplementedRelationRpcServer) mustEmbedUnimplementedRelationRpcServer() {}

func RegisterRelationRpcServer(s *grpc.Server, srv RelationRpcServer) {
	s.RegisterService(&_RelationRpc_serviceDesc, srv)
}

func _RelationRpc_AddFollow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFollowReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelationRpcServer).AddFollow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/relation.RelationRpc/AddFollow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelationRpcServer).AddFollow(ctx, req.(*AddFollowReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelationRpc_DeleteFollow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFollowReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelationRpcServer).DeleteFollow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/relation.RelationRpc/DeleteFollow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelationRpcServer).DeleteFollow(ctx, req.(*DeleteFollowReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelationRpc_GetFollowList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFollowListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelationRpcServer).GetFollowList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/relation.RelationRpc/GetFollowList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelationRpcServer).GetFollowList(ctx, req.(*GetFollowListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelationRpc_GetFollowerList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFollowerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelationRpcServer).GetFollowerList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/relation.RelationRpc/GetFollowerList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelationRpcServer).GetFollowerList(ctx, req.(*GetFollowerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelationRpc_GetFriendList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFriendListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelationRpcServer).GetFriendList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/relation.RelationRpc/GetFriendList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelationRpcServer).GetFriendList(ctx, req.(*GetFriendListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelationRpc_GetFollowerCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFollowerCountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelationRpcServer).GetFollowerCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/relation.RelationRpc/GetFollowerCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelationRpcServer).GetFollowerCount(ctx, req.(*GetFollowerCountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelationRpc_GetFollowCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFollowCountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelationRpcServer).GetFollowCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/relation.RelationRpc/GetFollowCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelationRpcServer).GetFollowCount(ctx, req.(*GetFollowCountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelationRpc_GetFriendCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFriendCountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelationRpcServer).GetFriendCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/relation.RelationRpc/GetFriendCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelationRpcServer).GetFriendCount(ctx, req.(*GetFriendCountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelationRpc_CheckIsFollow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckIsFollowReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelationRpcServer).CheckIsFollow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/relation.RelationRpc/CheckIsFollow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelationRpcServer).CheckIsFollow(ctx, req.(*CheckIsFollowReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _RelationRpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "relation.RelationRpc",
	HandlerType: (*RelationRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddFollow",
			Handler:    _RelationRpc_AddFollow_Handler,
		},
		{
			MethodName: "DeleteFollow",
			Handler:    _RelationRpc_DeleteFollow_Handler,
		},
		{
			MethodName: "GetFollowList",
			Handler:    _RelationRpc_GetFollowList_Handler,
		},
		{
			MethodName: "GetFollowerList",
			Handler:    _RelationRpc_GetFollowerList_Handler,
		},
		{
			MethodName: "GetFriendList",
			Handler:    _RelationRpc_GetFriendList_Handler,
		},
		{
			MethodName: "GetFollowerCount",
			Handler:    _RelationRpc_GetFollowerCount_Handler,
		},
		{
			MethodName: "GetFollowCount",
			Handler:    _RelationRpc_GetFollowCount_Handler,
		},
		{
			MethodName: "GetFriendCount",
			Handler:    _RelationRpc_GetFriendCount_Handler,
		},
		{
			MethodName: "CheckIsFollow",
			Handler:    _RelationRpc_CheckIsFollow_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "relation.proto",
}
