// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.4
// source: favor.proto

package favor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FavorReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid  int64 `protobuf:"varint,1,opt,name=Userid,proto3" json:"Userid,omitempty"`
	VideoId int64 `protobuf:"varint,2,opt,name=VideoId,proto3" json:"VideoId,omitempty"`
}

func (x *FavorReq) Reset() {
	*x = FavorReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_favor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FavorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavorReq) ProtoMessage() {}

func (x *FavorReq) ProtoReflect() protoreflect.Message {
	mi := &file_favor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavorReq.ProtoReflect.Descriptor instead.
func (*FavorReq) Descriptor() ([]byte, []int) {
	return file_favor_proto_rawDescGZIP(), []int{0}
}

func (x *FavorReq) GetUserid() int64 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *FavorReq) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

type FavorResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FavorResp) Reset() {
	*x = FavorResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_favor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FavorResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavorResp) ProtoMessage() {}

func (x *FavorResp) ProtoReflect() protoreflect.Message {
	mi := &file_favor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavorResp.ProtoReflect.Descriptor instead.
func (*FavorResp) Descriptor() ([]byte, []int) {
	return file_favor_proto_rawDescGZIP(), []int{1}
}

type DisFavorReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  int64 `protobuf:"varint,1,opt,name=Userid,proto3" json:"Userid,omitempty"`
	VideoId int64 `protobuf:"varint,2,opt,name=VideoId,proto3" json:"VideoId,omitempty"`
}

func (x *DisFavorReq) Reset() {
	*x = DisFavorReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_favor_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisFavorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisFavorReq) ProtoMessage() {}

func (x *DisFavorReq) ProtoReflect() protoreflect.Message {
	mi := &file_favor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisFavorReq.ProtoReflect.Descriptor instead.
func (*DisFavorReq) Descriptor() ([]byte, []int) {
	return file_favor_proto_rawDescGZIP(), []int{2}
}

func (x *DisFavorReq) GetUserid() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DisFavorReq) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

type DisFavorResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DisFavorResp) Reset() {
	*x = DisFavorResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_favor_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisFavorResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisFavorResp) ProtoMessage() {}

func (x *DisFavorResp) ProtoReflect() protoreflect.Message {
	mi := &file_favor_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisFavorResp.ProtoReflect.Descriptor instead.
func (*DisFavorResp) Descriptor() ([]byte, []int) {
	return file_favor_proto_rawDescGZIP(), []int{3}
}

type FavorListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid int64 `protobuf:"varint,1,opt,name=Userid,proto3" json:"Userid,omitempty"`
}

func (x *FavorListReq) Reset() {
	*x = FavorListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_favor_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FavorListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavorListReq) ProtoMessage() {}

func (x *FavorListReq) ProtoReflect() protoreflect.Message {
	mi := &file_favor_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavorListReq.ProtoReflect.Descriptor instead.
func (*FavorListReq) Descriptor() ([]byte, []int) {
	return file_favor_proto_rawDescGZIP(), []int{4}
}

func (x *FavorListReq) GetUserid() int64 {
	if x != nil {
		return x.Userid
	}
	return 0
}

type FavorListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Videos []*Video `protobuf:"bytes,1,rep,name=Videos,proto3" json:"Videos,omitempty"`
}

func (x *FavorListResp) Reset() {
	*x = FavorListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_favor_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FavorListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavorListResp) ProtoMessage() {}

func (x *FavorListResp) ProtoReflect() protoreflect.Message {
	mi := &file_favor_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavorListResp.ProtoReflect.Descriptor instead.
func (*FavorListResp) Descriptor() ([]byte, []int) {
	return file_favor_proto_rawDescGZIP(), []int{5}
}

func (x *FavorListResp) GetVideos() []*Video {
	if x != nil {
		return x.Videos
	}
	return nil
}

type Video struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Author      *User  `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Title       string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	PlayUrl     string `protobuf:"bytes,4,opt,name=play_url,json=playUrl,proto3" json:"play_url,omitempty"`
	CoverUrl    string `protobuf:"bytes,5,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	CreateTime  string `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime  string `protobuf:"bytes,7,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	VideoSha256 string `protobuf:"bytes,8,opt,name=video_sha256,json=videoSha256,proto3" json:"video_sha256,omitempty"`
}

func (x *Video) Reset() {
	*x = Video{}
	if protoimpl.UnsafeEnabled {
		mi := &file_favor_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Video) ProtoMessage() {}

func (x *Video) ProtoReflect() protoreflect.Message {
	mi := &file_favor_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Video.ProtoReflect.Descriptor instead.
func (*Video) Descriptor() ([]byte, []int) {
	return file_favor_proto_rawDescGZIP(), []int{6}
}

func (x *Video) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Video) GetAuthor() *User {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *Video) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Video) GetPlayUrl() string {
	if x != nil {
		return x.PlayUrl
	}
	return ""
}

func (x *Video) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *Video) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *Video) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

func (x *Video) GetVideoSha256() string {
	if x != nil {
		return x.VideoSha256
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Avatar          string `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	BackgroundImage string `protobuf:"bytes,7,opt,name=background_image,json=backgroundImage,proto3" json:"background_image,omitempty"`
	Signature       string `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
	IsFollow        bool   `protobuf:"varint,9,opt,name=is_follow,json=isFollow,proto3" json:"is_follow,omitempty"`
	FollowCount     int64  `protobuf:"varint,10,opt,name=follow_count,json=followCount,proto3" json:"follow_count,omitempty"`
	FollowerCount   int64  `protobuf:"varint,11,opt,name=follower_count,json=followerCount,proto3" json:"follower_count,omitempty"`
	TotalFavorited  string `protobuf:"bytes,12,opt,name=total_favorited,json=totalFavorited,proto3" json:"total_favorited,omitempty"`
	WorkCount       int64  `protobuf:"varint,13,opt,name=work_count,json=workCount,proto3" json:"work_count,omitempty"`
	FavoriteCount   int64  `protobuf:"varint,14,opt,name=favorite_count,json=favoriteCount,proto3" json:"favorite_count,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_favor_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_favor_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_favor_proto_rawDescGZIP(), []int{7}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *User) GetBackgroundImage() string {
	if x != nil {
		return x.BackgroundImage
	}
	return ""
}

func (x *User) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *User) GetIsFollow() bool {
	if x != nil {
		return x.IsFollow
	}
	return false
}

func (x *User) GetFollowCount() int64 {
	if x != nil {
		return x.FollowCount
	}
	return 0
}

func (x *User) GetFollowerCount() int64 {
	if x != nil {
		return x.FollowerCount
	}
	return 0
}

func (x *User) GetTotalFavorited() string {
	if x != nil {
		return x.TotalFavorited
	}
	return ""
}

func (x *User) GetWorkCount() int64 {
	if x != nil {
		return x.WorkCount
	}
	return 0
}

func (x *User) GetFavoriteCount() int64 {
	if x != nil {
		return x.FavoriteCount
	}
	return 0
}

type FavorNumReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoId int64 `protobuf:"varint,1,opt,name=VideoId,proto3" json:"VideoId,omitempty"`
}

func (x *FavorNumReq) Reset() {
	*x = FavorNumReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_favor_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FavorNumReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavorNumReq) ProtoMessage() {}

func (x *FavorNumReq) ProtoReflect() protoreflect.Message {
	mi := &file_favor_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavorNumReq.ProtoReflect.Descriptor instead.
func (*FavorNumReq) Descriptor() ([]byte, []int) {
	return file_favor_proto_rawDescGZIP(), []int{8}
}

func (x *FavorNumReq) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

type FavorNumResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num int64 `protobuf:"varint,1,opt,name=Num,proto3" json:"Num,omitempty"`
}

func (x *FavorNumResp) Reset() {
	*x = FavorNumResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_favor_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FavorNumResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavorNumResp) ProtoMessage() {}

func (x *FavorNumResp) ProtoReflect() protoreflect.Message {
	mi := &file_favor_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavorNumResp.ProtoReflect.Descriptor instead.
func (*FavorNumResp) Descriptor() ([]byte, []int) {
	return file_favor_proto_rawDescGZIP(), []int{9}
}

func (x *FavorNumResp) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type IsFavorReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  int64 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	VideoId int64 `protobuf:"varint,2,opt,name=VideoId,proto3" json:"VideoId,omitempty"`
}

func (x *IsFavorReq) Reset() {
	*x = IsFavorReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_favor_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsFavorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsFavorReq) ProtoMessage() {}

func (x *IsFavorReq) ProtoReflect() protoreflect.Message {
	mi := &file_favor_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsFavorReq.ProtoReflect.Descriptor instead.
func (*IsFavorReq) Descriptor() ([]byte, []int) {
	return file_favor_proto_rawDescGZIP(), []int{10}
}

func (x *IsFavorReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *IsFavorReq) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

type IsFavorResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsFavor bool `protobuf:"varint,1,opt,name=IsFavor,proto3" json:"IsFavor,omitempty"`
}

func (x *IsFavorResp) Reset() {
	*x = IsFavorResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_favor_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsFavorResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsFavorResp) ProtoMessage() {}

func (x *IsFavorResp) ProtoReflect() protoreflect.Message {
	mi := &file_favor_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsFavorResp.ProtoReflect.Descriptor instead.
func (*IsFavorResp) Descriptor() ([]byte, []int) {
	return file_favor_proto_rawDescGZIP(), []int{11}
}

func (x *IsFavorResp) GetIsFavor() bool {
	if x != nil {
		return x.IsFavor
	}
	return false
}

type FavorNumOfUserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
}

func (x *FavorNumOfUserReq) Reset() {
	*x = FavorNumOfUserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_favor_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FavorNumOfUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavorNumOfUserReq) ProtoMessage() {}

func (x *FavorNumOfUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_favor_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavorNumOfUserReq.ProtoReflect.Descriptor instead.
func (*FavorNumOfUserReq) Descriptor() ([]byte, []int) {
	return file_favor_proto_rawDescGZIP(), []int{12}
}

func (x *FavorNumOfUserReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type FavorNumOfUserResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FavorNumOfUser int64 `protobuf:"varint,1,opt,name=FavorNumOfUser,proto3" json:"FavorNumOfUser,omitempty"`
}

func (x *FavorNumOfUserResp) Reset() {
	*x = FavorNumOfUserResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_favor_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FavorNumOfUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavorNumOfUserResp) ProtoMessage() {}

func (x *FavorNumOfUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_favor_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavorNumOfUserResp.ProtoReflect.Descriptor instead.
func (*FavorNumOfUserResp) Descriptor() ([]byte, []int) {
	return file_favor_proto_rawDescGZIP(), []int{13}
}

func (x *FavorNumOfUserResp) GetFavorNumOfUser() int64 {
	if x != nil {
		return x.FavorNumOfUser
	}
	return 0
}

type FavoredNumOfUserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
}

func (x *FavoredNumOfUserReq) Reset() {
	*x = FavoredNumOfUserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_favor_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FavoredNumOfUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoredNumOfUserReq) ProtoMessage() {}

func (x *FavoredNumOfUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_favor_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoredNumOfUserReq.ProtoReflect.Descriptor instead.
func (*FavoredNumOfUserReq) Descriptor() ([]byte, []int) {
	return file_favor_proto_rawDescGZIP(), []int{14}
}

func (x *FavoredNumOfUserReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type FavoredNumOfUserResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FavoredNumOfUser int64 `protobuf:"varint,1,opt,name=FavoredNumOfUser,proto3" json:"FavoredNumOfUser,omitempty"`
}

func (x *FavoredNumOfUserResp) Reset() {
	*x = FavoredNumOfUserResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_favor_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FavoredNumOfUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoredNumOfUserResp) ProtoMessage() {}

func (x *FavoredNumOfUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_favor_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoredNumOfUserResp.ProtoReflect.Descriptor instead.
func (*FavoredNumOfUserResp) Descriptor() ([]byte, []int) {
	return file_favor_proto_rawDescGZIP(), []int{15}
}

func (x *FavoredNumOfUserResp) GetFavoredNumOfUser() int64 {
	if x != nil {
		return x.FavoredNumOfUser
	}
	return 0
}

var File_favor_proto protoreflect.FileDescriptor

var file_favor_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x66,
	0x61, 0x76, 0x6f, 0x72, 0x22, 0x3c, 0x0a, 0x08, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x52, 0x65, 0x71,
	0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x69, 0x64, 0x65,
	0x6f, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x56, 0x69, 0x64, 0x65, 0x6f,
	0x49, 0x64, 0x22, 0x0b, 0x0a, 0x09, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x3f, 0x0a, 0x0b, 0x44, 0x69, 0x73, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x12, 0x16,
	0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x64,
	0x22, 0x0e, 0x0a, 0x0c, 0x44, 0x69, 0x73, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x22, 0x26, 0x0a, 0x0c, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x69, 0x64, 0x22, 0x35, 0x0a, 0x0d, 0x46, 0x61, 0x76, 0x6f,
	0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x24, 0x0a, 0x06, 0x56, 0x69, 0x64,
	0x65, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x66, 0x61, 0x76, 0x6f,
	0x72, 0x2e, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x06, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x22,
	0xef, 0x01, 0x0a, 0x05, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x23, 0x0a, 0x06, 0x61, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x66, 0x61, 0x76, 0x6f,
	0x72, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x75, 0x72, 0x6c,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x55, 0x72, 0x6c, 0x12,
	0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x55, 0x72, 0x6c, 0x12, 0x1f, 0x0a, 0x0b,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1f, 0x0a,
	0x0b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x21,
	0x0a, 0x0c, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x73, 0x68, 0x61, 0x32, 0x35, 0x36, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x53, 0x68, 0x61, 0x32, 0x35,
	0x36, 0x22, 0xe1, 0x02, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x29, 0x0a, 0x10, 0x62, 0x61, 0x63, 0x6b, 0x67, 0x72,
	0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0f, 0x62, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x12, 0x21, 0x0a, 0x0c,
	0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0b, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x25, 0x0a, 0x0e, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65,
	0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f,
	0x66, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x64, 0x12,
	0x1d, 0x0a, 0x0a, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x0d, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x77, 0x6f, 0x72, 0x6b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x25,
	0x0a, 0x0e, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x0e, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x27, 0x0a, 0x0b, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x4e, 0x75,
	0x6d, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x64, 0x22, 0x20,
	0x0a, 0x0c, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10,
	0x0a, 0x03, 0x4e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x4e, 0x75, 0x6d,
	0x22, 0x3e, 0x0a, 0x0a, 0x49, 0x73, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x12, 0x16,
	0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x64,
	0x22, 0x27, 0x0a, 0x0b, 0x49, 0x73, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x18, 0x0a, 0x07, 0x49, 0x73, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x49, 0x73, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x22, 0x2b, 0x0a, 0x11, 0x46, 0x61, 0x76,
	0x6f, 0x72, 0x4e, 0x75, 0x6d, 0x4f, 0x66, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x16,
	0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x3c, 0x0a, 0x12, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x4e,
	0x75, 0x6d, 0x4f, 0x66, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x26, 0x0a, 0x0e,
	0x46, 0x61, 0x76, 0x6f, 0x72, 0x4e, 0x75, 0x6d, 0x4f, 0x66, 0x55, 0x73, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x4e, 0x75, 0x6d, 0x4f, 0x66,
	0x55, 0x73, 0x65, 0x72, 0x22, 0x2d, 0x0a, 0x13, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x65, 0x64, 0x4e,
	0x75, 0x6d, 0x4f, 0x66, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x22, 0x42, 0x0a, 0x14, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x65, 0x64, 0x4e, 0x75,
	0x6d, 0x4f, 0x66, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x10, 0x46,
	0x61, 0x76, 0x6f, 0x72, 0x65, 0x64, 0x4e, 0x75, 0x6d, 0x4f, 0x66, 0x55, 0x73, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x65, 0x64, 0x4e, 0x75,
	0x6d, 0x4f, 0x66, 0x55, 0x73, 0x65, 0x72, 0x32, 0x9e, 0x03, 0x0a, 0x08, 0x46, 0x61, 0x76, 0x6f,
	0x72, 0x52, 0x70, 0x63, 0x12, 0x33, 0x0a, 0x08, 0x44, 0x69, 0x73, 0x46, 0x61, 0x76, 0x6f, 0x72,
	0x12, 0x12, 0x2e, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x2e, 0x44, 0x69, 0x73, 0x46, 0x61, 0x76, 0x6f,
	0x72, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x2e, 0x44, 0x69, 0x73,
	0x46, 0x61, 0x76, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x05, 0x46, 0x61, 0x76,
	0x6f, 0x72, 0x12, 0x0f, 0x2e, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x2e, 0x46, 0x61, 0x76, 0x6f, 0x72,
	0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x2e, 0x46, 0x61, 0x76, 0x6f,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x36, 0x0a, 0x09, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x13, 0x2e, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x2e, 0x46, 0x61, 0x76, 0x6f, 0x72,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x2e,
	0x46, 0x61, 0x76, 0x6f, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x33, 0x0a,
	0x08, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x4e, 0x75, 0x6d, 0x12, 0x12, 0x2e, 0x66, 0x61, 0x76, 0x6f,
	0x72, 0x2e, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e,
	0x66, 0x61, 0x76, 0x6f, 0x72, 0x2e, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x4e, 0x75, 0x6d, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x30, 0x0a, 0x07, 0x49, 0x73, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x12, 0x11, 0x2e,
	0x66, 0x61, 0x76, 0x6f, 0x72, 0x2e, 0x49, 0x73, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x52, 0x65, 0x71,
	0x1a, 0x12, 0x2e, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x2e, 0x49, 0x73, 0x46, 0x61, 0x76, 0x6f, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x45, 0x0a, 0x0e, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x4e, 0x75, 0x6d,
	0x4f, 0x66, 0x55, 0x73, 0x65, 0x72, 0x12, 0x18, 0x2e, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x2e, 0x46,
	0x61, 0x76, 0x6f, 0x72, 0x4e, 0x75, 0x6d, 0x4f, 0x66, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x1a, 0x19, 0x2e, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x2e, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x4e, 0x75,
	0x6d, 0x4f, 0x66, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x4b, 0x0a, 0x10, 0x46,
	0x61, 0x76, 0x6f, 0x72, 0x65, 0x64, 0x4e, 0x75, 0x6d, 0x4f, 0x66, 0x55, 0x73, 0x65, 0x72, 0x12,
	0x1a, 0x2e, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x2e, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x65, 0x64, 0x4e,
	0x75, 0x6d, 0x4f, 0x66, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x66, 0x61,
	0x76, 0x6f, 0x72, 0x2e, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x65, 0x64, 0x4e, 0x75, 0x6d, 0x4f, 0x66,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x66, 0x61,
	0x76, 0x6f, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_favor_proto_rawDescOnce sync.Once
	file_favor_proto_rawDescData = file_favor_proto_rawDesc
)

func file_favor_proto_rawDescGZIP() []byte {
	file_favor_proto_rawDescOnce.Do(func() {
		file_favor_proto_rawDescData = protoimpl.X.CompressGZIP(file_favor_proto_rawDescData)
	})
	return file_favor_proto_rawDescData
}

var file_favor_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_favor_proto_goTypes = []interface{}{
	(*FavorReq)(nil),             // 0: favor.FavorReq
	(*FavorResp)(nil),            // 1: favor.FavorResp
	(*DisFavorReq)(nil),          // 2: favor.DisFavorReq
	(*DisFavorResp)(nil),         // 3: favor.DisFavorResp
	(*FavorListReq)(nil),         // 4: favor.FavorListReq
	(*FavorListResp)(nil),        // 5: favor.FavorListResp
	(*Video)(nil),                // 6: favor.video
	(*User)(nil),                 // 7: favor.user
	(*FavorNumReq)(nil),          // 8: favor.FavorNumReq
	(*FavorNumResp)(nil),         // 9: favor.FavorNumResp
	(*IsFavorReq)(nil),           // 10: favor.IsFavorReq
	(*IsFavorResp)(nil),          // 11: favor.IsFavorResp
	(*FavorNumOfUserReq)(nil),    // 12: favor.FavorNumOfUserReq
	(*FavorNumOfUserResp)(nil),   // 13: favor.FavorNumOfUserResp
	(*FavoredNumOfUserReq)(nil),  // 14: favor.FavoredNumOfUserReq
	(*FavoredNumOfUserResp)(nil), // 15: favor.FavoredNumOfUserResp
}
var file_favor_proto_depIdxs = []int32{
	6,  // 0: favor.FavorListResp.Videos:type_name -> favor.video
	7,  // 1: favor.video.author:type_name -> favor.user
	2,  // 2: favor.FavorRpc.DisFavor:input_type -> favor.DisFavorReq
	0,  // 3: favor.FavorRpc.Favor:input_type -> favor.FavorReq
	4,  // 4: favor.FavorRpc.FavorList:input_type -> favor.FavorListReq
	8,  // 5: favor.FavorRpc.FavorNum:input_type -> favor.FavorNumReq
	10, // 6: favor.FavorRpc.IsFavor:input_type -> favor.IsFavorReq
	12, // 7: favor.FavorRpc.FavorNumOfUser:input_type -> favor.FavorNumOfUserReq
	14, // 8: favor.FavorRpc.FavoredNumOfUser:input_type -> favor.FavoredNumOfUserReq
	3,  // 9: favor.FavorRpc.DisFavor:output_type -> favor.DisFavorResp
	1,  // 10: favor.FavorRpc.Favor:output_type -> favor.FavorResp
	5,  // 11: favor.FavorRpc.FavorList:output_type -> favor.FavorListResp
	9,  // 12: favor.FavorRpc.FavorNum:output_type -> favor.FavorNumResp
	11, // 13: favor.FavorRpc.IsFavor:output_type -> favor.IsFavorResp
	13, // 14: favor.FavorRpc.FavorNumOfUser:output_type -> favor.FavorNumOfUserResp
	15, // 15: favor.FavorRpc.FavoredNumOfUser:output_type -> favor.FavoredNumOfUserResp
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_favor_proto_init() }
func file_favor_proto_init() {
	if File_favor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_favor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FavorReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_favor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FavorResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_favor_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DisFavorReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_favor_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DisFavorResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_favor_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FavorListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_favor_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FavorListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_favor_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Video); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_favor_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_favor_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FavorNumReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_favor_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FavorNumResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_favor_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsFavorReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_favor_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsFavorResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_favor_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FavorNumOfUserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_favor_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FavorNumOfUserResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_favor_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FavoredNumOfUserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_favor_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FavoredNumOfUserResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_favor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_favor_proto_goTypes,
		DependencyIndexes: file_favor_proto_depIdxs,
		MessageInfos:      file_favor_proto_msgTypes,
	}.Build()
	File_favor_proto = out.File
	file_favor_proto_rawDesc = nil
	file_favor_proto_goTypes = nil
	file_favor_proto_depIdxs = nil
}
