// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.4
// source: favor.proto

package favor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DisFavorReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid  int64  `protobuf:"varint,1,opt,name=Userid,proto3" json:"Userid,omitempty"`
	Videoid int64  `protobuf:"varint,2,opt,name=Videoid,proto3" json:"Videoid,omitempty"`
	Token   string `protobuf:"bytes,3,opt,name=Token,proto3" json:"Token,omitempty"`
}

func (x *DisFavorReq) Reset() {
	*x = DisFavorReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_favor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisFavorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisFavorReq) ProtoMessage() {}

func (x *DisFavorReq) ProtoReflect() protoreflect.Message {
	mi := &file_favor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisFavorReq.ProtoReflect.Descriptor instead.
func (*DisFavorReq) Descriptor() ([]byte, []int) {
	return file_favor_proto_rawDescGZIP(), []int{0}
}

func (x *DisFavorReq) GetUserid() int64 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *DisFavorReq) GetVideoid() int64 {
	if x != nil {
		return x.Videoid
	}
	return 0
}

func (x *DisFavorReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type DisFavorResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DisFavorResp) Reset() {
	*x = DisFavorResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_favor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisFavorResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisFavorResp) ProtoMessage() {}

func (x *DisFavorResp) ProtoReflect() protoreflect.Message {
	mi := &file_favor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisFavorResp.ProtoReflect.Descriptor instead.
func (*DisFavorResp) Descriptor() ([]byte, []int) {
	return file_favor_proto_rawDescGZIP(), []int{1}
}

type FavorReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid  int64  `protobuf:"varint,1,opt,name=Userid,proto3" json:"Userid,omitempty"`
	Videoid int64  `protobuf:"varint,2,opt,name=Videoid,proto3" json:"Videoid,omitempty"`
	Token   string `protobuf:"bytes,3,opt,name=Token,proto3" json:"Token,omitempty"`
}

func (x *FavorReq) Reset() {
	*x = FavorReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_favor_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FavorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavorReq) ProtoMessage() {}

func (x *FavorReq) ProtoReflect() protoreflect.Message {
	mi := &file_favor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavorReq.ProtoReflect.Descriptor instead.
func (*FavorReq) Descriptor() ([]byte, []int) {
	return file_favor_proto_rawDescGZIP(), []int{2}
}

func (x *FavorReq) GetUserid() int64 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *FavorReq) GetVideoid() int64 {
	if x != nil {
		return x.Videoid
	}
	return 0
}

func (x *FavorReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type FavorResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FavorResp) Reset() {
	*x = FavorResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_favor_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FavorResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavorResp) ProtoMessage() {}

func (x *FavorResp) ProtoReflect() protoreflect.Message {
	mi := &file_favor_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavorResp.ProtoReflect.Descriptor instead.
func (*FavorResp) Descriptor() ([]byte, []int) {
	return file_favor_proto_rawDescGZIP(), []int{3}
}

type FavorListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid int64  `protobuf:"varint,1,opt,name=Userid,proto3" json:"Userid,omitempty"`
	Token  string `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
}

func (x *FavorListReq) Reset() {
	*x = FavorListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_favor_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FavorListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavorListReq) ProtoMessage() {}

func (x *FavorListReq) ProtoReflect() protoreflect.Message {
	mi := &file_favor_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavorListReq.ProtoReflect.Descriptor instead.
func (*FavorListReq) Descriptor() ([]byte, []int) {
	return file_favor_proto_rawDescGZIP(), []int{4}
}

func (x *FavorListReq) GetUserid() int64 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *FavorListReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type FavorListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Videoids []int64 `protobuf:"varint,1,rep,packed,name=Videoids,proto3" json:"Videoids,omitempty"`
}

func (x *FavorListResp) Reset() {
	*x = FavorListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_favor_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FavorListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavorListResp) ProtoMessage() {}

func (x *FavorListResp) ProtoReflect() protoreflect.Message {
	mi := &file_favor_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavorListResp.ProtoReflect.Descriptor instead.
func (*FavorListResp) Descriptor() ([]byte, []int) {
	return file_favor_proto_rawDescGZIP(), []int{5}
}

func (x *FavorListResp) GetVideoids() []int64 {
	if x != nil {
		return x.Videoids
	}
	return nil
}

type FavorNumReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vedioid int64 `protobuf:"varint,1,opt,name=Vedioid,proto3" json:"Vedioid,omitempty"`
}

func (x *FavorNumReq) Reset() {
	*x = FavorNumReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_favor_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FavorNumReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavorNumReq) ProtoMessage() {}

func (x *FavorNumReq) ProtoReflect() protoreflect.Message {
	mi := &file_favor_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavorNumReq.ProtoReflect.Descriptor instead.
func (*FavorNumReq) Descriptor() ([]byte, []int) {
	return file_favor_proto_rawDescGZIP(), []int{6}
}

func (x *FavorNumReq) GetVedioid() int64 {
	if x != nil {
		return x.Vedioid
	}
	return 0
}

type FavorNumResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num int64 `protobuf:"varint,1,opt,name=Num,proto3" json:"Num,omitempty"`
}

func (x *FavorNumResp) Reset() {
	*x = FavorNumResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_favor_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FavorNumResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavorNumResp) ProtoMessage() {}

func (x *FavorNumResp) ProtoReflect() protoreflect.Message {
	mi := &file_favor_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavorNumResp.ProtoReflect.Descriptor instead.
func (*FavorNumResp) Descriptor() ([]byte, []int) {
	return file_favor_proto_rawDescGZIP(), []int{7}
}

func (x *FavorNumResp) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

var File_favor_proto protoreflect.FileDescriptor

var file_favor_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x66,
	0x61, 0x76, 0x6f, 0x72, 0x22, 0x55, 0x0a, 0x0b, 0x44, 0x69, 0x73, 0x46, 0x61, 0x76, 0x6f, 0x72,
	0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x56,
	0x69, 0x64, 0x65, 0x6f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x0e, 0x0a, 0x0c, 0x44,
	0x69, 0x73, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x22, 0x52, 0x0a, 0x08, 0x46,
	0x61, 0x76, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x69, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22,
	0x0b, 0x0a, 0x09, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x22, 0x3c, 0x0a, 0x0c,
	0x46, 0x61, 0x76, 0x6f, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x2b, 0x0a, 0x0d, 0x46, 0x61,
	0x76, 0x6f, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x56,
	0x69, 0x64, 0x65, 0x6f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x08, 0x56,
	0x69, 0x64, 0x65, 0x6f, 0x69, 0x64, 0x73, 0x22, 0x27, 0x0a, 0x0b, 0x46, 0x61, 0x76, 0x6f, 0x72,
	0x4e, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x65, 0x64, 0x69, 0x6f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x56, 0x65, 0x64, 0x69, 0x6f, 0x69, 0x64,
	0x22, 0x20, 0x0a, 0x0c, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x10, 0x0a, 0x03, 0x4e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x4e,
	0x75, 0x6d, 0x32, 0xd8, 0x01, 0x0a, 0x08, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x52, 0x70, 0x63, 0x12,
	0x33, 0x0a, 0x08, 0x44, 0x69, 0x73, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x12, 0x12, 0x2e, 0x66, 0x61,
	0x76, 0x6f, 0x72, 0x2e, 0x44, 0x69, 0x73, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x1a,
	0x13, 0x2e, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x2e, 0x44, 0x69, 0x73, 0x46, 0x61, 0x76, 0x6f, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x05, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x12, 0x0f, 0x2e,
	0x66, 0x61, 0x76, 0x6f, 0x72, 0x2e, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x10,
	0x2e, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x2e, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x36, 0x0a, 0x09, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x13, 0x2e,
	0x66, 0x61, 0x76, 0x6f, 0x72, 0x2e, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x1a, 0x14, 0x2e, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x2e, 0x46, 0x61, 0x76, 0x6f, 0x72,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x33, 0x0a, 0x08, 0x46, 0x61, 0x76, 0x6f,
	0x72, 0x4e, 0x75, 0x6d, 0x12, 0x12, 0x2e, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x2e, 0x46, 0x61, 0x76,
	0x6f, 0x72, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x66, 0x61, 0x76, 0x6f, 0x72,
	0x2e, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x42, 0x09, 0x5a,
	0x07, 0x2e, 0x2f, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_favor_proto_rawDescOnce sync.Once
	file_favor_proto_rawDescData = file_favor_proto_rawDesc
)

func file_favor_proto_rawDescGZIP() []byte {
	file_favor_proto_rawDescOnce.Do(func() {
		file_favor_proto_rawDescData = protoimpl.X.CompressGZIP(file_favor_proto_rawDescData)
	})
	return file_favor_proto_rawDescData
}

var file_favor_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_favor_proto_goTypes = []interface{}{
	(*DisFavorReq)(nil),   // 0: favor.DisFavorReq
	(*DisFavorResp)(nil),  // 1: favor.DisFavorResp
	(*FavorReq)(nil),      // 2: favor.FavorReq
	(*FavorResp)(nil),     // 3: favor.FavorResp
	(*FavorListReq)(nil),  // 4: favor.FavorListReq
	(*FavorListResp)(nil), // 5: favor.FavorListResp
	(*FavorNumReq)(nil),   // 6: favor.FavorNumReq
	(*FavorNumResp)(nil),  // 7: favor.FavorNumResp
}
var file_favor_proto_depIdxs = []int32{
	0, // 0: favor.FavorRpc.DisFavor:input_type -> favor.DisFavorReq
	2, // 1: favor.FavorRpc.Favor:input_type -> favor.FavorReq
	4, // 2: favor.FavorRpc.FavorList:input_type -> favor.FavorListReq
	6, // 3: favor.FavorRpc.FavorNum:input_type -> favor.FavorNumReq
	1, // 4: favor.FavorRpc.DisFavor:output_type -> favor.DisFavorResp
	3, // 5: favor.FavorRpc.Favor:output_type -> favor.FavorResp
	5, // 6: favor.FavorRpc.FavorList:output_type -> favor.FavorListResp
	7, // 7: favor.FavorRpc.FavorNum:output_type -> favor.FavorNumResp
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_favor_proto_init() }
func file_favor_proto_init() {
	if File_favor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_favor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DisFavorReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_favor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DisFavorResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_favor_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FavorReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_favor_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FavorResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_favor_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FavorListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_favor_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FavorListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_favor_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FavorNumReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_favor_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FavorNumResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_favor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_favor_proto_goTypes,
		DependencyIndexes: file_favor_proto_depIdxs,
		MessageInfos:      file_favor_proto_msgTypes,
	}.Build()
	File_favor_proto = out.File
	file_favor_proto_rawDesc = nil
	file_favor_proto_goTypes = nil
	file_favor_proto_depIdxs = nil
}
