name: Docker Build and Push Chat
on:
  push:
    branches:
      - main

jobs:
  # chat-rpc
  build-and-push-chat-rpc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create and push chat-rpc Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./server/chat/rpc/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_IMAGE }}chat-rpc:latest
          platforms: linux/amd64,linux/arm64  # 构建多个架构的镜像
  # chat-api
  build-and-push-chat-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create and push chat-api Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./server/chat/api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_IMAGE }}chat-api:latest
          platforms: linux/amd64,linux/arm64  # 构建多个架构的镜像

  # chat-mq
  build-and-push-chat-mq:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create and push chat-mq Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./server/chat/mq/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_IMAGE }}chat-mq:latest
          platforms: linux/amd64,linux/arm64  # 构建多个架构的镜像
