name: Docker Build and Push
on:
  push:
    branches:
      - dev

jobs:
  build-and-push-gophertok-user-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create and push gophertok-user-api Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./server/user/api/Dockerfile
          push: true
          tags: liuxian123/gophertok-user-api:latest
          platforms: linux/amd64,linux/arm64  # 构建多个架构的镜像

  build-and-push-gophertok-user-rpc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create and push gophertok-user-rpc Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./server/user/rpc/Dockerfile
          push: true
          tags: liuxian123/gophertok-user-rpc:latest
          platforms: linux/amd64,linux/arm64  # 构建多个架构的镜像
