name: Docker Build and Push
on:
  push:
    branches:
      - main

jobs:
# user-api
  build-and-push-user-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create and push user-api Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./server/user/api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_IMAGE }}user-api:latest
          platforms: linux/amd64,linux/arm64  # 构建多个架构的镜像
# user-rpc
  build-and-push-user-rpc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create and push user-rpc Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./server/user/rpc/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_IMAGE }}user-rpc:latest
          platforms: linux/amd64,linux/arm64  # 构建多个架构的镜像



# video-rpc
  build-and-push-video-rpc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create and push video-rpc Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./server/video/rpc/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_IMAGE }}video-rpc:latest
          platforms: linux/amd64,linux/arm64  # 构建多个架构的镜像
# video-api
  build-and-push-video-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create and push video-api Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./server/video/api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_IMAGE }}video-api:latest
          platforms: linux/amd64,linux/arm64  # 构建多个架构的镜像

# video-mq
  build-and-push-video-mq:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create and push video-mq Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./server/video/kmq/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_IMAGE }}video-mq:latest
          platforms: linux/amd64,linux/arm64  # 构建多个架构的镜像  





  # chat-rpc
  build-and-push-chat-rpc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create and push chat-rpc Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./server/chat/rpc/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_IMAGE }}chat-rpc:latest
          platforms: linux/amd64,linux/arm64  # 构建多个架构的镜像
# chat-api
  build-and-push-chat-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create and push chat-api Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./server/chat/api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_IMAGE }}chat-api:latest
          platforms: linux/amd64,linux/arm64  # 构建多个架构的镜像

# chat-mq
  build-and-push-chat-mq:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create and push chat-mq Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./server/chat/mq/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_IMAGE }}chat-mq:latest
          platforms: linux/amd64,linux/arm64  # 构建多个架构的镜像



  # comment-rpc
  build-and-push-comment-rpc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create and push comment-rpc Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./server/comment/rpc/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_IMAGE }}comment-rpc:latest
          platforms: linux/amd64,linux/arm64  # 构建多个架构的镜像
  # comment-api
  build-and-push-comment-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create and push comment-api Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./server/comment/api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_IMAGE }}comment-api:latest
          platforms: linux/amd64,linux/arm64  # 构建多个架构的镜像

  # comment-mq
  build-and-push-comment-mq:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create and push comment-mq Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./server/comment/mq/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_IMAGE }}comment-mq:latest
          platforms: linux/amd64,linux/arm64  # 构建多个架构的镜像

  # favor-api
  build-and-push-favor-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create and push favor-api Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./server/favor/api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_IMAGE }}favor-api:latest
          platforms: linux/amd64,linux/arm64  # 构建多个架构的镜像



  # favor-rpc
  build-and-push-favor-rpc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create and push favor-rpc Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./server/favor/rpc/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_IMAGE }}favor-rpc:latest
          platforms: linux/amd64,linux/arm64  # 构建多个架构的镜像


  # relation-rpc
  build-and-push-relation-rpc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create and push relation-rpc Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./server/relation/rpc/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_IMAGE }}relation-rpc:latest
          platforms: linux/amd64,linux/arm64  # 构建多个架构的镜像
  # relation-api
  build-and-push-relation-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create and push relation-api Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./server/relation/api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_IMAGE }}relation-api:latest
          platforms: linux/amd64,linux/arm64  # 构建多个架构的镜像

  # relation-mq
  build-and-push-relation-mq:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create and push relation-mq Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./server/relation/kmq/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_IMAGE }}relation-mq:latest
          platforms: linux/amd64,linux/arm64  # 构建多个架构的镜像