name: Docker Build and Push xx
on:
  workflow_dispatch:
    inputs:
      parameter_name:
        description: 'go'
        required: true


jobs:


  # video-rpc
  build-and-push-video-rpc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create and push video-rpc Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./server/video/rpc/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_IMAGE }}video-rpc:latest
          platforms: linux/amd64,linux/arm64  # 构建多个架构的镜像

      - name: SSH into the remote server and perform actions
        uses: appleboy/ssh-action@v0.3.0
        with:
          host: ${{ secrets.REMOTE_SERVER_HOST }}
          username: ${{ secrets.REMOTE_SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/project/gophertok
            sudo /usr/local/bin/docker-compose -f docker-compose.yaml stop video-rpc
            ${{ secrets.SSH_PRIVATE_KEY }}
            sudo /usr/local/bin/docker-compose -f docker-compose.yaml rm -f video-rpc
            sudo docker image rm ${{ secrets.DOCKERHUB_IMAGE }}video-rpc:latest
            sudo /usr/local/bin/docker-compose -f docker-compose.yaml up -d video-rpc
            

