name: Docker Build and Push xx
on:
  workflow_dispatch:
    inputs:
      parameter_name:
        description: 'go'
        required: true


jobs:


  # video-rpc
  build-and-push-video-rpc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create and push video-rpc Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./server/video/rpc/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_IMAGE }}video-rpc:latest
          platforms: linux/amd64,linux/arm64  # 构建多个架构的镜像

