name: Docker Build and Push Relation
on:
  push:
    branches:
      - main

jobs:

  # relation-rpc
  build-and-push-relation-rpc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create and push relation-rpc Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./server/relation/rpc/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_IMAGE }}relation-rpc:latest
          platforms: linux/amd64,linux/arm64  # 构建多个架构的镜像
  # relation-api
  build-and-push-relation-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create and push relation-api Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./server/relation/api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_IMAGE }}relation-api:latest
          platforms: linux/amd64,linux/arm64  # 构建多个架构的镜像

  # relation-mq
  build-and-push-relation-mq:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create and push relation-mq Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./server/relation/kmq/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_IMAGE }}relation-mq:latest
          platforms: linux/amd64,linux/arm64  # 构建多个架构的镜像

