name: Docker Build and Push User
on:
  push:
    branches:
      - dev
    author:
      - liuxianloveqiqi  # Replace with the actual GitHub username
jobs:
  # user-api
  build-and-push-user-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create and push user-api Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./server/user/api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_IMAGE }}user-api:latest
          platforms: linux/amd64,linux/arm64  # 构建多个架构的镜像
  # user-rpc
  build-and-push-user-rpc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create and push user-rpc Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./server/user/rpc/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_IMAGE }}user-rpc:latest
          platforms: linux/amd64,linux/arm64  # 构建多个架构的镜像

  # user-mq
  build-and-push-user-mq:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create and push user-mq Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./server/user/kmq/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_IMAGE }}user-mq:latest
          platforms: linux/amd64,linux/arm64  # 构建多个架构的镜像


