name: Docker Build and Push Video2
on:
  push:
    branches:
      - dev
    author:
      - liuxianloveqiqi  # Replace with the actual GitHub username

jobs:

  # video-rpc

  # video-api
  build-and-push-video-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create and push video-api Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./server/video/api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_IMAGE }}video-api:latest
          platforms: linux/amd64,linux/arm64  # 构建多个架构的镜像


